name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so we have access to the source files
      - uses: actions/checkout@v4

      # Deploy the static frontend directory straight to GitHub Pages.  We don't run any build
      # steps because the frontend is pure HTML/JS/CSS.  The peaceiris GH Pages action will
      # copy everything under `frontend` into the gh-pages branch and serve it from there.
      - name: Deploy static site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend
