name: Refresh knowledge graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install backend requirements
        run: pip install -r backend/requirements.txt
      - name: Execute ingestion plan
        env:
          GRAPH_BACKEND: memory
        run: python -m backend.graph.cli ingest --limit 50
